SELECT 'INSERT INTO BILL (BILL_ID, CUS_ID, COU_ID, FOUND_DATE, PAID_AMOUNT, HOS_ID) VALUES (' || BILL_ID || ', ' || CUS_ID || ', ' || COU_ID || ', ' || FOUND_DATE || ', ' || PAID_AMOUNT || ', ' || HOS_ID || ');'
FROM BILL;

SELECT 'INSERT INTO COUPON (COU_ID, NAME, TYPE, PRICE) VALUES (' || COU_ID || ', ' || NAME || ', ' || TYPE || ', ' || PRICE || ');'
FROM COUPON;

SELECT 'INSERT INTO CUSTOMER (CUS_ID, PHONE_NUM, FOUND_DATE, BIRTHDAY, GENDER, NAME, PASSWORD, BALANCE, VIPLEVEL) VALUES (' || CUS_ID || ', ' || PHONE_NUM || ', ' || FOUND_DATE || ', ' || BIRTHDAY || ', ' || GENDER || ', ' || NAME || ', ' || PASSWORD || ', ' || BALANCE || ', ' || VIPLEVEL || ');'
FROM CUSTOMER;

SELECT 'INSERT INTO CUS_COU (CUS_ID, COU_ID) VALUES (' || CUS_ID || ', ' || COU_ID || ');'
FROM CUS_COU;

SELECT 'INSERT INTO DEPARTMENT (DEP_ID, NAME) VALUES (' || DEP_ID || ', ' || NAME || ');'
FROM DEPARTMENT;

SELECT 'INSERT INTO FINANCIAL (HOS_ID, FINANCE_MONTH, INCOME, PAYOUT) VALUES (' || HOS_ID || ', ' || FINANCE_MONTH || ', ' || INCOME || ', ' || PAYOUT || ');'
FROM FINANCIAL;

SELECT 'INSERT INTO GOODS (G_ID, NAME, PRICE, PRODUCER) VALUES (' || G_ID || ', ' || NAME || ', ' || PRICE || ', ' || PRODUCER || ');'
FROM GOODS;

SELECT 'INSERT INTO HOSPITAL (HOS_ID, DATE_OF_ESTABLISHMENT, NAME, QUALIFICATION, ADDRESS, PHONE_NUMBER) VALUES (' || HOS_ID || ', ' || DATE_OF_ESTABLISHMENT || ', ' || NAME || ', ' || QUALIFICATION || ', ' || ADDRESS || ', ' || PHONE_NUMBER || ');'
FROM HOSPITAL;

SELECT 'INSERT INTO HOS_DEP (H_ID, D_ID) VALUES (' || H_ID || ', ' || D_ID || ');'
FROM HOS_DEP;

SELECT 'INSERT INTO INVENTORY (STORAGE, HOS_ID, G_ID, SELL_BY_DATE) VALUES (' || STORAGE || ', ' || HOS_ID || ', ' || G_ID || ', ' || SELL_BY_DATE || ');'
FROM INVENTORY;

-- SELECT 'INSERT INTO MEMBER (VIPLEVEL, DISCOUNT) VALUES (' || VIPLEVEL || ', ' || DISCOUNT || ');'
-- FROM MEMBER;

SELECT 'INSERT INTO OPERATE (PROJ_ID, SER_ID, BILL_ID, FOUND_DATE, EXE_STATE, OP_TIME_ID) VALUES (' || PROJ_ID || ', ' || SER_ID || ', ' || BILL_ID || ', ' || FOUND_DATE || ', ' || EXE_STATE || ', ' || OP_TIME_ID || ');'
FROM OPERATE;

SELECT 'INSERT INTO OPERATE_TIME (OP_TIME_ID, DAY, START_TIME, END_TIME, STATUS, ROOM_ID) VALUES (' || OP_TIME_ID || ', ' || DAY || ', ' || START_TIME || ', ' || END_TIME || ', ' || STATUS || ', ' || ROOM_ID || ');'
FROM OPERATE_TIME;

SELECT 'INSERT INTO OPERATING_ROOM (ROOM_ID, HOS_ID) VALUES (' || ROOM_ID || ', ' || HOS_ID || ');'
FROM OPERATING_ROOM;

SELECT 'INSERT INTO PROJECT (PROJ_ID, NAME, PRICE, FOUND_DATE) VALUES (' || PROJ_ID || ', ' || NAME || ', ' || PRICE || ', ' || FOUND_DATE || ');'
FROM PROJECT;

SELECT 'INSERT INTO PROJ_GOOD (PROJ_ID, G_ID) VALUES (' || PROJ_ID || ', ' || G_ID || ');'
FROM PROJ_GOOD;

SELECT 'INSERT INTO SERVER (SER_ID, JOINED_DATE, NAME, PASSWORD, POSITION, PHONE_NUM, HOS_ID, DEP_ID, WORK_TIME_ID, IS_WORK_TODAY, GENDER, BIRTHDAY, BASICSALARY, TAKEHOMEPAY) VALUES (' || SER_ID || ', ' || JOINED_DATE || ', ' || NAME || ', ' || PASSWORD || ', ' || POSITION || ', ' || PHONE_NUM || ', ' || HOS_ID || ', ' || DEP_ID || ', ' || WORK_TIME_ID || ', ' || IS_WORK_TODAY || ', ' || GENDER || ', ' || BIRTHDAY || ', ' || BASICSALARY || ', ' || TAKEHOMEPAY || ');'
FROM SERVER;

-- SELECT 'INSERT INTO WORK_TIME (WORK_TIME_ID, DAY1, DAY2, DAY3, DAY4, DAY5, DAY6, DAY7) VALUES (' || WORK_TIME_ID || ', ' || DAY1 || ', ' || DAY2 || ', ' || DAY3 || ', ' || DAY4 || ', ' || DAY5 || ', ' || DAY6 || ', ' || DAY7 || ');'
-- FROM WORK_TIME;